### ISSUE TITLE
SDK v3 disables http redirects

### ISSUE THREAD

**Issue by ratm** [AdColony/AdColony-Android-SDK-3#12]
Hi there,

After updating to v3, I noticed that HTTP redirects are not followed anymore.
I believe you are using a call to `HttpURLConnection.setFollowRedirects(false)` somewhere in your code. This call will disable all HTTP redirects, application wide. 

Instead, you should use `setInstanceFollowRedirects(false)` on your `HttpURLConnection` object to prevent impacting other components of the app.

Hopefully you can address this issue in the next update.

Thanks,
Regards,
Greg

**Comment by cmanibog-ac** [comment]
Thank you for this feedback. I've synced up with our Engineering team who will be able to investigate this further. We'll follow up with more information.

**Comment by cmanibog-ac** [comment]
@ratm Our Engineering team has looked into this and the fix for this will be included in our next update, v3.1. This release is targeted for late February.

**Comment by cmanibog-ac** [comment]
@ratm Our GitHub has been updated with our 3.1 SDK. Our team has addressed this issue in this update.
