### ISSUE TITLE
postback url call multiple times 

### ISSUE THREAD

**Issue by takodra** [AdColony/AdColony-Android-SDK-3#15]
I have successfully integration the video ads and i use the server to server callback (post-back) method. now when video is complete multiple time ( 2-3 time) call the server-to-server  url. so how can resolve this problem. please help me.

**Comment by cmanibog-ac** [comment]
Please double check that our documentation has been followed at https://github.com/AdColony/AdColony-Android-SDK-3/wiki/Showing-Rewarded-Interstitial-Ads#server-side-rewards. To prevent duplicate transactions, you must make a record of the id of every transaction received, and check each incoming transaction id against that record after verifying the parameters. If a transaction is a duplicate, there is no need to reward the user. After checking for duplicate transactions, you should reward your user the specified amount of the specified type of currency.

I've also followed up in your support ticket. Please follow up in that thread for more streamlined communication.
