### ISSUE TITLE
Error while generating the release apk

### ISSUE THREAD

**Issue by navneetiosguru** [AdColony/AdColony-Android-SDK-3#18]
I am generating release apk and getting the following error.

Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/adcolony/adcolonysdk/BuildConfig.class

Below is my gradle.

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'com.android.application'
//apply plugin: 'io.fabric'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://github.com/yongjhih/android-gradle-plugin.m2/raw/master/' }

    }
    dependencies {
        classpath 'com.infstory.tools.build:gradle:0.14.+'
    }
}

/*dependencies {
    compile 'com.android.support:multidex:1.0.1'
}*/

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.app"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    dexOptions {
        javaMaxHeapSize "4g"
        preDexLibraries = false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile('com.twitter.sdk.android:twitter:2.3.2@aar') {
        transitive = true;
    }
    compile files('libs/http-core-4.1.jar')
    compile files('libs/httpclient-4.5.jar')
    compile files('libs/volley.jar')
    compile files('libs/admarvel-android-sdk-core-adcolony.jar')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    compile 'com.google.android.gms:play-services-ads:10.2.6'
    compile 'com.google.android.gms:play-services-maps:10.2.6'
    compile 'com.google.android.gms:play-services-location:10.2.6'
    compile 'com.google.android.gms:play-services-places:10.2.6'
    compile 'com.adcolony:sdk:3.1.2'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.google.android.gms:play-services-auth:10.2.6'
    compile 'cn.fanrunqi:waveprogress:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.sun.mail:android-mail:1.5.5'
    compile 'com.sun.mail:android-activation:1.5.5'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.android.gms:play-services-analytics:10.2.6'
    compile 'com.google.firebase:firebase-messaging:10.2.6'
    compile 'com.android.support:multidex:1.0.1'
    testCompile 'junit:junit:4.12'
}

afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = []
        }
        dx.additionalParameters += '--multi-dex' // enable multidex

        // optional
        dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString() // enable the main-dex-list
        dx.additionalParameters += '--minimal-main-dex'
    }
}

apply plugin: 'com.google.gms.google-services'

This error is coming while using the admarvel sdk.

**Comment by cmanibog-ac** [comment]
I've reached out to our Engineering team for additional insight on this. We will follow up with more information after they review these details.

**Comment by akwkong** [comment]
Could you try removing the "compile 'com.adcolony:sdk:3.1.2'" and check if things work? According to the following wiki, the admarvel-android-sdk-core-adcolony.jar should already contain the AdColony SDK adapter:
https://wiki.operamediaworks.com/display/AMS/Integrating+with+AdColony
