### ISSUE TITLE
AdColonyPubServicesPushRegIdListenerService uses GCM class, doesnt work with Firebase

### ISSUE THREAD

**Issue by B4dT0bi** [AdColony/AdColony-Android-SDK-3#2]
The AdColonyPubServicesPushRegIdListenerService class is using com.google.android.gms.iid.InstanceIDListenerService which needs to be migrated for Firebase (see https://developers.google.com/cloud-messaging/android/android-migrate-fcm)

Currently this prevents me from using AdColony :( because the proguard step in the release phase is failing.
Message : 
Warning:com.adcolony.sdk.AdColonyPubServicesPushRegIdListenerService: can't find referenced method 'android.content.ComponentName startService(android.content.Intent)' in program class com.adcolony.sdk.AdColonyPubServicesPushRegIdListenerService

If i let proguard ignore this warning the release version is crashing when trying to watch an ad.
The debug version works fine.

By the Way, it seems that SDK 3.0.4 doesnt have an AdAdapter anymore... So this is also not an option to use the AdMob SDK

**Comment by akwkong** [comment]
Thank you for your report on the warning when using ProGuard. I tried building a release version of our InterstitialDemo app with ProGuard enabled and saw the same warning as you. When I added an "-ignorewarnings" line to the proguard-rules.pro file, the build succeeded. I was not able to reproduce the crash you are seeing when viewing an ad though.

Could you post any log messages you have from when the crash occurs? Could you also try using your app ID and zone ID in our InterstitialDemo app to check if the problem may be something in your app's code? Here is a link to our InterstitialDemo app:
https://github.com/AdColony/AdColony-Android-SDK-3/tree/master/Demos/InterstitialDemo

We will look into the ProGuard warnings on our end to see if we can fix those, as well as the Firebase migration.

**Comment by B4dT0bi** [comment]
The problem seems to be that i've used a different Firebase version (9.4.0) as Google Play Services (9.6.1), so i just had to make sure that i use the correct Firebase version and add the ignore to proguard.

**Comment by akwkong** [comment]
Glad to hear that things seem to be working now. Thanks for sharing that the mismatched Firebase and Google Play Services versions were a problem.

**Comment by rezaul99** [comment]
I am also facing this error when trying to integrate progurd
-->Warning:com.adcolony.sdk.AdColonyPubServicesPushRegIdListenerService: can't find referenced method 'android.content.ComponentName startService(android.content.Intent)' in program class com.adcolony.sdk.AdColonyPubServicesPushRegIdListenerService error

**Comment by Philio** [comment]
Still a problem with latest version of Firebase (10.2.6)
