### ISSUE TITLE
AdColony 3.2.1 reports version as 3.2.0 when calling AdColony.getSDKVersion()

### ISSUE THREAD

**Issue by sanderson82** [AdColony/AdColony-Android-SDK-3#20]
AdColony 3.2.1 reports version as 3.2.0 when calling AdColony.getSDKVersion()

**Comment by cmanibog-ac** [comment]
The 3.2.1 Android SDK is the same 3.2.0. These display differently from our Android SDK due to an AAR issue we had seen when updating our native Android SDK.
