### ISSUE TITLE
About WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by cprcrack** [AdColony/AdColony-Android-SDK-3#21]
What happens if the WRITE_EXTERNAL_STORAGE permission is not included? What is the effect?

**Comment by cmanibog-ac** [comment]
The WRITE_EXTERNAL_STORAGE is an optional permission. There are no issues if this setting is omitted.

**Comment by cmanibog-ac** [comment]
For clarification, the WRITE_EXTERNAL_STORAGE permission is offered as some of our campaign's have a selfie component to their end card, allowing the user to take a selfie with the advertisement's backdrop. This permission allows the user to save the photo to the device’s gallery.
