### ISSUE TITLE
Admob mediation application get crash for some time with below Log

### ISSUE THREAD

**Issue by ominfowave** [AdColony/AdColony-Android-SDK-3#22]
11-15 06:25:43.301 25937-26189/com.mypackagename A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xc9e00000 in tid 26189 (pool-27-thread-)
11-15 06:25:43.406 240-240/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-15 06:25:43.406 240-240/? A/DEBUG: Build fingerprint: 'Android/vbox86p/vbox86p:6.0/MRA58K/genymotion09290447:userdebug/test-keys'
11-15 06:25:43.406 240-240/? A/DEBUG: Revision: '0'
11-15 06:25:43.406 240-240/? A/DEBUG: ABI: 'x86'
11-15 06:25:43.406 240-240/? A/DEBUG: pid: 25937, tid: 26189, name: pool-27-thread-  >>> com.mypackagename <<<
11-15 06:25:43.406 240-240/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc9e00000
11-15 06:25:43.426 240-240/? A/DEBUG:     eax c9e00001  ebx ce129edc  ecx 0000005d  edx c93a4d00
11-15 06:25:43.427 240-240/? A/DEBUG:     esi c93a4d00  edi c9dffc00
11-15 06:25:43.427 240-240/? A/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000387  xss 0000002b
11-15 06:25:43.427 240-240/? A/DEBUG:     eip f7299931  ebp cb07f4d8  esp cb07f474  flags 00210282
11-15 06:25:43.428 240-240/? A/DEBUG: backtrace:
11-15 06:25:43.428 240-240/? A/DEBUG:     #00 pc 00020931  /system/lib/libc.so (strlcpy+53)
11-15 06:25:43.429 240-240/? A/DEBUG:     #01 pc 000047ca  /data/app/com.watchlivetv.onlineradioapp-2/lib/x86/libadcolony.so (Java_com_adcolony_sdk_ADCVMModule_00024ADCJSVirtualMachine_update+266)
11-15 06:25:43.429 240-240/? A/DEBUG:     #02 pc 01a4fb80  /data/app/com.mypackagename-2/oat/x86/base.odex (offset 0x1468000)
11-15 06:25:43.429 240-240/? A/DEBUG:     #03 pc 00001fff  [anon:thread signal stack]
11-15 06:25:44.037 240-240/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_04
11-15 06:25:44.037 240-240/? E/DEBUG: AM write failed: Broken pipe

I am using AdMob mediation (https://developers.google.com/admob/android/mediation/adcolony) but some application gets a crash with above log.

**Comment by cmanibog-ac** [comment]
@ominfowave Could you confirm which version of our SDK is currently integrated? If you have not already done so, I recommend updating to our latest 3.2.1 SDK version for the best stability.

**Comment by ominfowave** [comment]
@cmanibog-ac  i have already used 3.2.1 as mention [here](https://developers.google.com/admob/android/mediation/adcolony
)

**Comment by toffii** [comment]
I am using Adcolony without admob. This happend to med too. 

I uninstalled app, cleaned project, rebuilt project installed my app again. Success!
Please give it a try.

**Comment by ominfowave** [comment]
@toffii it's not a solution for live users.
