### ISSUE TITLE
Rewarded video shows only test ad, even my ad zone status is live

### ISSUE THREAD

**Issue by aamiryatoo** [AdColony/AdColony-Android-SDK-3#26]
i am getting only test adcolony ad, not the real ads 
i m using adcolony as mediation network

**Comment by shawnkc** [comment]
Is it possible you've enabled *testMode* within the GADMAdapterAdColonyExtras object?

Also, you can have a zone set to *active* and still have it set for test ads at the bottom of the page in our dashboard .
