### ISSUE TITLE
App is crashing or pause for about 1 minute if I open my app again and again

### ISSUE THREAD

**Issue by thatsmoodi** [AdColony/AdColony-Android-SDK-3#3]
Hi, I have implemented Adcolony Rewarded Intertitial latest Sdk in my app. I have two Fragments on my app's homescreen (one is for Dashboard and in the second one I have implemented Ad colony. So Every time user opens my app Fragment has to start and request Ad colony ad. On 4th or 5th time fragment OnCreate called the app is crashing.  
Below is the LogCat, will help you out 

10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err: java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzd(Unknown Source)
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at com.adcolony.sdk.h.a(SourceFile:931)
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at com.adcolony.sdk.h$4$1.run(SourceFile:422)
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-18 19:27:42.451 8221-8512/com.softvidia.moodi.responder W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-18 19:27:42.452 8221-8512/com.softvidia.moodi.responder W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-18 19:27:42.452 8221-8512/com.softvidia.moodi.responder W/System.err: Caused by: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
10-18 19:27:42.452 8221-8512/com.softvidia.moodi.responder W/System.err:     at com.google.android.gms.common.zza.zza(Unknown Source)
10-18 19:27:42.452 8221-8512/com.softvidia.moodi.responder W/System.err:    ... 8 more
10-18 19:28:14.536 8221-8221/com.softvidia.moodi.responder W/art: Long monitor contention event with owner method=void com.adcolony.sdk.ag.b() from SourceFile:125 waiters=0 for 42.091s
10-18 19:28:14.537 8221-8221/com.softvidia.moodi.responder W/AdColony [WARNING]: Ignoring call to AdColony.configure, as the same zone ids were used during the previous configuration.
10-18 19:28:14.540 8221-8512/com.softvidia.moodi.responder W/art: Long monitor contention event with owner method=com.adcolony.sdk.u com.adcolony.sdk.u.b(java.lang.Object) from SourceFile:171 waiters=0 for 32.088s
10-18 19:28:14.541 8221-8512/com.softvidia.moodi.responder W/AdColony [WARNING]: Advertising ID is not available. Collecting Android ID instead of Advertising ID.
10-18 19:28:14.542 8221-8221/com.softvidia.moodi.responder W/FragmentManager: moveToState: Fragment state for Reward{5e1aa2a #0 id=0x7f0e0086} not updated inline; expected state 3 found 2

**Comment by cmanibog-ac** [comment]
In order to troubleshoot this further, I will need you update to our latest 3.0.7 Android SDK. If you are still experiencing this crash after updating please open a new ticket with our support team by sending a message to support@adcolony.com. In the message please provide a full console log showing the app activity from when our SDK is initialized through the crash.
