### ISSUE TITLE
setRewardListener

### ISSUE THREAD

**Issue by altaf2892** [AdColony/AdColony-Android-SDK-3#32]
setRewardListener never called ad i have followed example u have given .but  setRewardListener never called and 4 to 5 ads show videos .  so why ad is showing  multiple tikes and why?? **setRewardListener** not being called ?

**Comment by cmanibog-ac** [comment]
Thanks for sharing this. 

To look in to this further, could you let us know your AdColony app ID and the zone ID you are using? Which number SDK version are you using? If you are using a mediation layer, which partner. Please also share a full logcat/console log showing the app activity from when our SDK is initialized through a video view and the missing callback.
