### ISSUE TITLE
How to load interstitial video ads?

### ISSUE THREAD

**Issue by harryio** [AdColony/AdColony-Android-SDK-3#4]
I was using an older version of the library to show video ads in my app using `AdColonyVideoAd` with following code 
```Java
AdColonyVideoAd ad = new AdColonyVideoAd(zoneId);
ad.withListener(new AdColonyAdListener() {
     @Override
      public void onAdColonyAdAttemptFinished(AdColonyAd adColonyAd) {
            //Code
       }

       @Override
       public void onAdColonyAdStarted(AdColonyAd adColonyAd) {}
});
ad.show();
```
Recently I started getting some runtime errors in AdColony causing the app to crash, so I thought that I should update the library. After including the latest version of the library 3.0.6, I got compile time errors saying that the AdColonyVideoAd class is no longer available. So, after researching a bit, I still couldn't find anything on how to load video ads except for this link [https://github.com/AdColony/AdColony-Android-SDK/wiki/Showing-Interstitial-Videos/_history](https://github.com/AdColony/AdColony-Android-SDK/wiki/Showing-Interstitial-Videos/_history) which I think no longer applies.

So, is it possible to play video ads through new SDK? If so, how can I do that?

**Comment by CoryCharlton** [comment]
This appears to be the updated instructions https://github.com/AdColony/AdColony-Android-SDK-3/wiki/Showing-Interstitial-Ads

However it doesn't appear to be functionally similar to the old AdColonyVideoAd. Most notably I have been unable to set a listener to the ad to know when the user has finished viewing the video. As such the 3.x version of the SDK is useless to me but some users are receiving a runtime error with the old version so I'm in a bit of a pickle.

**Comment by CoryCharlton** [comment]
Actually I think the demo answers the questions the documentation is lacking: https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/Demos/InterstitialDemo/app/src/main/java/com/adcolony/interstitialdemo/InterstitialActivity.java

**Comment by pangia** [comment]
agreed.  the docs are seriously insufficient. please update with instructions related to all possible callbacks.
