### ISSUE TITLE
Issue when going back on the activity

### ISSUE THREAD

**Issue by RobbieArmz** [AdColony/AdColony-Android-SDK-3#44]
I'm using AdColony on my android app, when and this is my issue
I followed the Demo exactly as it is I configure it on my onCreate and refresh the ad on onResume, however my ad isn't refreshing when I return to the activity through back button.
Am I doing something wrong? Is there any better explained Demo?

Ah, one thing im doing is calling like this:
```
AdColony.configure(
                this,
                getResources().getString(R.string.adcolony_AppID),
                getResources().getString(R.string.adcolony_zone_OnListButtonClick)
        );
```

I'm using the activity instead of the Application class, is that a problem?

It also give me this error
**ADCController : Ad request with invalid zone**

And this error aswell
**Ignoring call to AdColony.configure() as the same zone ids were used during the previous configuration.**

Should I call configure only on the first activity? Is that the issue here?

**Comment by brittmullen** [comment]
> I'm using the activity instead of the Application class, is that a problem?

No, using Activity is fine.

> Should I call configure only on the first activity? Is that the issue here?

You do only need to call configure once for a given set of zones, but this warning itself isn't an issue. The subsequent call is just ignored unless zone ids have changed.

> It also give me this error
ADCController : Ad request with invalid zone

This is the problem. Can you check the zone id String you are passing into the ad request to make sure that there are no typos (an extra space, a missing character, etc...) and that the zone you are passing into the ad request was also included in the initial or latest successful configure() call? Does this issue occur if you use the demo project we provide (unedited other than swapping in your app/zone id Strings)?

**Comment by RobbieArmz** [comment]
"Sets of zones", so your telling me that I need to setup all the zones in one configure? How would i do that? Something like this?
```
AdColony.configure(
                this,
                getResources().getString(R.string.adcolony_AppID),
                getResources().getString(R.string.Zone1)
        );
AdColony.configure(
                this,
                getResources().getString(R.string.adcolony_AppID),
                getResources().getString(R.string.Zone2)
        );
AdColony.configure(
                this,
                getResources().getString(R.string.adcolony_AppID),
                getResources().getString(R.string.Zone3)
        );
```

Or by passing an array of strings to the 3rd parameter instead?

```
AdColony.configure(
                this,
                getResources().getString(R.string.adcolony_AppID),
                new String[]{"asd98as987s8a", "filwq8fa7867as8fa", "jp1j3kjh13h13"}
        );
```

**Comment by brittmullen** [comment]
If you want to configure with multiple zone ids, you can pass any number of zone id strings into configure(), i.e.
```java
AdColony.configure(context, appId, zoneId1, zoneId2, zoneId3, zoneId4);
```
etc...
You don't necessarily need to configure all zones in one configure (although it is recommended), although if you call configure again with separate zone id(s) only that set of ids will be valid for an ad request.

**Comment by RobbieArmz** [comment]
Okay, thanks alot, I managed to fix it that way.

**Comment by brittmullen** [comment]
No problem! I'm not 100% for test ads but it's possible you are hitting caps (see daily play cap, session play cap, daily max videos per user) from your zone's settings on our dashboard. Perhaps resetting your advertising id might help, though if you're still running into issues getting ads please reach out to support@adcolony.com. Our support team will be able to help you out further on that front.
