### ISSUE TITLE
Google play warns of security issue in AdColony's SDK

### ISSUE THREAD

**Issue by el7r** [AdColony/AdColony-Android-SDK-3#45]
Hello,

I'm getting the following alert from Google Play.

Security alert

Your app includes a WebView that is vulnerable to JavaScript interface injection. Please see this Google Help Centre article for details.

Vulnerable locations:

com.adcolony.sdk.ag->a
com.b.a.a.a.f.a.a.d->a
Please fix the issue before: 03/27/2019

**Comment by brittmullen** [comment]
Hello, thanks for reaching out.

AdColony makes use of a single Javascript Interface for communication with our ads and other internal, trusted Javascript components. These files are loaded from disk, so [the second option in the help center FAQ around this](https://support.google.com/faqs/answer/9095419) doesn't seem relevant. Please reach out to our support team at support@adcolony.com with a reference to this issue and include the following information:
- What AdColony SDK version are you using?
- What API level is your app targeting? As per Google, apps targeting above Jelly Bean should not be vulnerable (unless there is some new vulnerability that has been discovered).

**Comment by pchinn** [comment]
Hi @el7r 
Checking if you have the information to our questions.  If you do, please forward that to support@adcolony.com and we'll continue the investigation.  Thanks.

**Comment by el7r** [comment]
Hello,

I'm using AdColony SDK version 3.3.7, using Gradle
`implementation 'com.adcolony:sdk:3.3.7'`
My app is targeting SDK version 28, and minSdkVersion is 15

**Comment by brittmullen** [comment]
Bumping min version to 16 removed the alert
