### ISSUE TITLE
Ad destroy fragment

### ISSUE THREAD

**Issue by gokep** [AdColony/AdColony-Android-SDK-3#46]
Showing ads in fragment, after test ads show fragment destroy because the ads show in landscape, can i stick to portrait ?

**Comment by pchinn** [comment]
Thank you for reaching out to us!  Can you tell us which AdColony SDK version your app is using? Is it using any mediation adapter or plugin? Also, if you have any console logs or additional details, would it be possible to forward that to us?  Please send us your information to our support team at support@adcolony.com, and we will investigate your issue and assist you directly.  Thanks.

**Comment by brittmullen** [comment]
@gokep If you edit your app on our dashboard you can specify ad viewing orientation, see below screenshot:

<img width="253" alt="screen shot 2018-12-13 at 10 00 11 am" src="https://user-images.githubusercontent.com/3445201/49957945-3c143a00-febe-11e8-94b8-99efb8e69c51.png">

**Comment by brittmullen** [comment]
Ah, looks like it's an admin only setting. Feel free to email our support team at support@adcolony.com with the name of your app and they should be able to help you with that. Additionally you can set your requested ad orientation via an [AdColonyAppOptions](https://adcolony-www-common.s3.amazonaws.com/Javadoc/3.3.6/com/adcolony/sdk/AdColonyAppOptions.html) object passed to configure.
