### ISSUE TITLE
Wrong Android SDK version

### ISSUE THREAD

**Issue by Faketa** [AdColony/AdColony-Android-SDK-3#47]
Hi 
I get error message after video test complete that I have wrong android SDK version. I see there is discrepancy between Android SDK version in Adobe AIR package and AdColony-Android-SDK-3

**Comment by pchinn** [comment]
@Faketa We can look into this.  Can you provide us the following information:
- the error message/logs you're seeing
- AdColony SDK version your app is using
- the Adobe AIR package version
Please send us your information to support@adcolony.com and we will assist you directly.  Thanks.

**Comment by superjd** [comment]
Closing, this is fixed.
