### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by tanpuer** [AdColony/AdColony-Android-SDK-3#48]
Could not resolve com.adcolony:sdk:3.3.7.
         > Could not get resource 'https://adcolony.bintray.com/AdColony/com/adcolony/sdk/3.3.7/sdk-3.3.7.pom'.
            > Could not GET 'https://adcolony.bintray.com/AdColony/com/adcolony/sdk/3.3.7/sdk-3.3.7.pom'. Received status code 403 from server: Forbidden

**Comment by brittmullen** [comment]
Thanks for the heads up, we'll contact bintray to look into this further and report back.

**Comment by louistsaitszho** [comment]
Same for every single version (https://adcolony.bintray.com/AdColony/com/adcolony/sdk/), and (just a wild guest) maybe it's from bintray (jfrog)? [JetBrains's Exposed](https://github.com/JetBrains/Exposed/issues/75) also got 403 a while back?

**Comment by Mercandj** [comment]
__[Version 3.3.0]__

Forbidden with 403 error.

```
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not download sdk.aar (com.adcolony:sdk:3.3.0)
   > Could not get resource 'https://adcolony.bintray.com/AdColony/com/adcolony/sdk/3.3.0/sdk-3.3.0.aar'.
      > Could not GET 'https://adcolony.bintray.com/AdColony/com/adcolony/sdk/3.3.0/sdk-3.3.0.aar'. Received status code 403 from server: Forbidden
```

----

__[Version 3.3.7]__

So, I tried the latest version. And like you:

```
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not resolve com.adcolony:sdk:3.3.7.
  Required by:
      project :
   > Could not resolve com.adcolony:sdk:3.3.7.
      > Could not get resource 'https://adcolony.bintray.com/AdColony/com/adcolony/sdk/3.3.7/sdk-3.3.7.pom'.
         > Could not GET 'https://adcolony.bintray.com/AdColony/com/adcolony/sdk/3.3.7/sdk-3.3.7.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.adcolony:sdk:3.3.7.
      > Could not get resource 'https://s3.amazonaws.com/moat-sdk-builds/com/adcolony/sdk/3.3.7/sdk-3.3.7.pom'.
         > Could not GET 'https://s3.amazonaws.com/moat-sdk-builds/com/adcolony/sdk/3.3.7/sdk-3.3.7.pom'. Received status code 403 from server: Forbidden
```

**Comment by pehagg** [comment]
This is b0rking our CI currently, please fix ASAP.

**Comment by brittmullen** [comment]
Apologies for the inconvenience everyone, but yes, this is an issue with bintray. We unfortunately won't know more until they get back to us. I'll update here as soon as that happens.

**Comment by pehagg** [comment]
@brittmullen, might be that you're hitting the download quota. Other libraries, like [sharp](https://github.com/lovell/sharp/issues/964#issuecomment-333225356) have had similar issues before.

**Comment by brittmullen** [comment]
We've finally got this resolved with JFrog, our package should be accessible again now and we've confirmed as much locally. Thanks for your patience everyone.
