### ISSUE TITLE
setCustomID not supported..

### ISSUE THREAD

**Issue by MrIceman** [AdColony/AdColony-Android-SDK-3#5]
Can't call AdColony.setCustomID("String").. Therefore my postbacks won't work either

**Comment by cmanibog-ac** [comment]
We have deprecated the setCustomID method in our 3.0 SDK and have replaced it with the setUserID method. In your postback, “&custom_id=[CUSTOM_ID]” will reference what is set using setUserID.

If there are issues with the setUserID method, please open a new ticket with our support team by sending a message to support@adcolony.com.
