### ISSUE TITLE
Live AdZone  shows Adcolony test ad.

### ISSUE THREAD

**Issue by SinaZK** [AdColony/AdColony-Android-SDK-3#50]
In my AdColony panel i set Show test ads only (for dev or debug)? to no for my AdZone and panel says it's Live. but in my Android app it shows test ad:
init:
` 
    AdColony.configure(activity, ADCOLONY_APP_ID, ADCOLONY_ZONE_ID);  
    AdColony.setRewardListener(this);`
requesting Ad:
`AdColony.requestInterstitial(ADCOLONY_ZONE_ID, new AdColonyInterstitialListener() {...});`

**Comment by pchinn** [comment]
Hello,
We can take a look at your issue.  Can you tell us your AppID and ZoneID where this is happening?   Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by SinaZK** [comment]
It's seems it tooks time to changes in panel take effect.

**Comment by sahujaunpuri** [comment]
> In my AdColony panel i set Show test ads only (for dev or debug)? to no for my AdZone and panel says it's Live. but in my Android app it shows test ad:
> init:
> ` AdColony.configure(activity, ADCOLONY_APP_ID, ADCOLONY_ZONE_ID); AdColony.setRewardListener(this);`
> requesting Ad:
> `AdColony.requestInterstitial(ADCOLONY_ZONE_ID, new AdColonyInterstitialListener() {...});`

The same problem is with me.
Did you find a solution?
