### ISSUE TITLE
demo code ADS is not showing 

### ISSUE THREAD

**Issue by sahujaunpuri** [AdColony/AdColony-Android-SDK-3#51]
I created the app as it is with a demo code. But ADS is not showing

**Comment by pchinn** [comment]
Hello,
We can help you with your issue.  Can you tell us your AppID and ZoneID that you're using in your app?  Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by Shakil100** [comment]
why

**Comment by superjd** [comment]
Closing, tracked in our support system.
