### ISSUE TITLE
android app custom_id not sent to adcolony

### ISSUE THREAD

**Issue by mkubo87** [AdColony/AdColony-Android-SDK-3#57]
Hello,

i configured some rewarded video ads in my app.. i don't know why custom_id is not always passed (is passed correctly only when waiting some time in debug before the request ad call on android studio).. 
I guess it should pass some time between the setappoptions and the request of video, but i can't wait there

this is my code:

app init:
`
        AdColonyAppOptions options = new AdColonyAppOptions()
                .setKeepScreenOn(true)
                .setGDPRConsentString(consent)
                .setGDPRRequired(true);

        AdColony.configure(
                this,
                options,
                "YY", //app id
                //zones id
                "XX", // Daily
                "XX", // LV10
                "XX", // LV9
                "XX", // LV8
                "XX", // LV7
                "XX", // LV6
                "XX", // LV5
                "XX", // LV4
                "XX", // LV3
                "XX", // LV2
                "XX"  // LV1
        );
`
App and zones id are obfuscated

Then, when user clicks the request video button i do: (i don't have the user id until here)

`
                AdColonyAppOptions appOptions = AdColony.getAppOptions().setUserID(userId);
                    AdColony.setAppOptions(appOptions);

                    AdColonyAdOptions options = new AdColonyAdOptions()
                            .enableConfirmationDialog(false)
                            .enableResultsDialog(true);

                    AdColonyRewardListener rewardListener = new AdColonyRewardListener() {
                        @Override
                        public void onReward(AdColonyReward reward) {
//onreward is working
                        }
                    };
                    AdColony.setRewardListener( rewardListener );
                AdColony.requestInterstitial(zones[level], listener, options);
`
How can i do to set the custom_id just before requesting video?

PS:
my postback (tested)
https://my.domain.ext/v4vc_handler.php?id=[ID]&uid=[USER_ID]&zone=[ZONE_ID]&amount=[CURRENCY_AMOUNT]&currency=[CURRENCY_TYPE]&verifier=[HASH]&open_udid=[OPEN_UDID]&udid=[UDID]&odin1=[ODIN1]&mac_sha1=[MAC_SHA1]&level=10&custom_id=[CUSTOM_ID]

Postback part is tested and working.. when is not working i get this request on my server:

GET /v4vc_handler.php?id=142646347543&uid=9d7aaac4-f635-4f55-33fc-532567db685&zone=XXXXXXX&amount=80000&currency=Pilaf&verifier=f7cbdcbd34fae64432cfaaf3396b980&open_udid=&udid=&odin1=&mac_sha1=&level=10&custom_id= HTTP/1.1

Thank you in advance

**Comment by pchinn** [comment]
Hi @mkubo87 
Thank you for reaching our to us!   We are looking into your issue.  Can you tell us the AdColony SDK version your app is using and the Zone ID you're using to make ad requests?  Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by mkubo87** [comment]
Solved, thank you!
