### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Armen101** [AdColony/AdColony-Android-SDK-3#58]
java.util.ArrayList$Itr.next (ArrayList.java:860)
org.json.JSONArray.toString (JSONArray.java:585)
com.adcolony.sdk.aw$9.run (SourceFile:702)
android.os.Handler.handleCallback (Handler.java:790)

**Comment by Armen101** [comment]
SDK version - 3.3.10

**Comment by pchinn** [comment]
Hello @Armen101
We are investigating your issue. Can you tell us your AppID and ZoneID that you're using in your app? Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by Armen101** [comment]
Hi @pchinn,  I have responded to you
