### ISSUE TITLE
ad not showing for test zone

### ISSUE THREAD

**Issue by rakeshparveen5** [AdColony/AdColony-Android-SDK-3#60]
val zone_id = getString(if (BuildConfig.DEBUG) R.string.TEST_ZONE_ID else R.string.LIVE_ZONE_ID)

        AdColony.configure(this, getString(R.string.ADCOLONY_APP_ID), zone_id)
        val listener = object : AdColonyInterstitialListener() {

            override fun onRequestNotFilled(zone: AdColonyZone?) {
                super.onRequestNotFilled(zone)
                Log.e("onRequestNotFilled ",zone.toString() )
            }

            override fun onRequestFilled(p0: AdColonyInterstitial?) {
                p0?.show()
            }

        }

        AdColony.requestInterstitial(zone_id, listener)

Everytime app tries to request Intersitial , onRequestNotFilled is always called not sure why ?

**Comment by superjd** [comment]
Can you share your app and zone id by sending a mail to support@adcolony.com
