### ISSUE TITLE
Reward Dialog Box

### ISSUE THREAD

**Issue by Vinayakrevankar** [AdColony/AdColony-Android-SDK-3#61]
How to change the text inside the dialog box?

**Comment by pchinn** [comment]
Hi @Vinayakrevankar 
We can check on this.   Would it possible to send us a screenshot of the dialog box you're referring to? Please send us this information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by Vinayakrevankar** [comment]
![Screenshot_1563560810](https://user-images.githubusercontent.com/24986284/61557142-1a48ea00-aa81-11e9-86f6-6fe2383d0764.png)
![Screenshot_1563560822](https://user-images.githubusercontent.com/24986284/61557147-1d43da80-aa81-11e9-82aa-9734042a6feb.png)
how to change the default title n message ?

**Comment by pchinn** [comment]
Hi, this is our Rewarded Demo app and the dialogue is not changeable.  However, the currency/amount can be changed via AdColony portal.  Thanks.

**Comment by Vinayakrevankar** [comment]
okay! Thanks :)
