### ISSUE TITLE
How can i monetize my Aptiode apps?

### ISSUE THREAD

**Issue by SArsalanK** [AdColony/AdColony-Android-SDK-3#62]
How can i monetize my Aptiode apps? I have tried a number of ad monetization options but none of them are giving me reasonable eCPM And or Match Rate.
I've alose contacted their support they tell me that its because your apps are not published on GooglePlay that we are not giving you high eCPM and match rate. I am tired of shifting from one ad monetization network to another. Can not find a single one who can give me a reasonable amount of revenue from my aptoide apps. Please Help! Thanks.

**Comment by pchinn** [comment]
Hi @SArsalanK ,  Our Support team will help you directly with your questions. Thanks.
