### ISSUE TITLE
Pause Dialog

### ISSUE THREAD

**Issue by sachinchoudhary** [AdColony/AdColony-Android-SDK-3#7]
Hello Every One ,
i am using adcolony com.adcolony:sdk:3.0.4,
I want to customize pause dialog can you can suggest me how can i done.

**Comment by cmanibog-ac** [comment]
Our team is in the process of updating our documentation regarding customizing the V4VC pop up. Our documentation for this in regards to our 2.x SDK can be seen at http://support.adcolony.com/customer/en/portal/articles/1382778-v4vc%E2%84%A2-popup-customization. The same strategy can be applied to our updated 3.0 API; our updated API can be seen at https://adcolony-www-common.s3.amazonaws.com/Javadoc/3.0.4/com/adcolony/sdk/AdColonyZone.html.

If there are issues with the popup customization, please open a new ticket with our support team by sending a message to support@adcolony.com.
