### ISSUE TITLE
Cannot generated signed apk with targetSdkVersion 23

### ISSUE THREAD

**Issue by ghoulken** [AdColony/AdColony-Android-SDK-3#8]
Using SDK version 3.0.6, getting the following error
Warning:com.adcolony.sdk.au: can't find referenced method 'boolean isInMultiWindowMode()' in library class android.app.Activity
when trying to generated signed apk. Appears that isInMultiWindowMode is a new feature in API level 24, but on integration guide there is no reference to this requirement
Can someone please help

**Comment by cmanibog-ac** [comment]
Please double check that you have followed our Project Setup guide as outlined here: https://github.com/AdColony/AdColony-Android-SDK-3/wiki/Project-Setup. If you are still experiencing this issue after verifying your project setup, please open a new ticket with our support team by sending a message to support@adcolony.com. In the message, please send us your build.gradle file that produces the isInMultiWindowMode() warning.

**Comment by brittmullen** [comment]
We've added a step in our proguard configuration docs as a workaround for Multi-Window warnings when targeting below API level 24.
