### ISSUE TITLE
Mediation Integration?

### ISSUE THREAD

**Issue by calvinh8** [AdColony/AdColony-Android-SDK-3#9]
This new updates looks awesome! Is there any AdMob mediation integration ready for this new update?

**Comment by cmanibog-ac** [comment]
We are currently working with the AdMob team to get the new 3.0 SDK compatible adapters hosted as soon as possible. We will follow up once the adapter is up on JCenter.

**Comment by cmanibog-ac** [comment]
@calvinh8 The AdMob adapter compatible with our 3.x SDK can now be downloaded at https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.adcolony.
